config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :events, only: %i[new index show create]
  resources :users, only: %i[new create show]
  resources :attendances, only: %i[create destroy]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  root to: 'events#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User', foreign_key: 'user_id'
  belongs_to :attended_event, class_name: 'Event', foreign_key: 'event_id'
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, :description, :date, presence: true
  belongs_to :creator, class_name: 'User', foreign_key: :user_id
  has_many :attendances, dependent: :destroy
  has_many :attendees, through: :attendances, class_name: 'User', foreign_key: :user_id

  scope :past, -> { where('date<?', Time.now).order('created_at DESc') }
  scope :upcoming, -> { where('date>?', Time.now).order('created_at DESc') }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
  has_many :events, dependent: :destroy
  has_many :attendances, dependent: :destroy
  has_many :attended_events, class_name: 'Event', foreign_key: 'event_id', through: :attendances
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :events_attendance, :events_created

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def authorization
    redirect_to login_path alert: 'Sign in' unless logged_in?
  end

  def events_created
    current_user.events
  end

  def events_attendance
    current_user.attended_events
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def create
    @attend = Attendance.new
    @attend.user_id = current_user.id
    @attend.event_id = params[:event_id]
    redirect_to current_user, notice: 'Event added to attending list' if @attend.valid? && @attend.save
  end

  def destroy
    @attend = Attendance.find_by(event_id: params[:id])
    redirect_to current_user, notice: 'Event removed from attending list' if @attend.valid? && @attend.destroy
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  @event = Event.new

  before_action :authorization
  helper_method :events_user_attending, :test

  def new
    @event = Event.new
  end

  def index
    @events = Event.all
    @past_events = Event.past.paginate(page: params[:page], per_page: 2).order(created_at: :desc)
    @upcoming_events = Event.upcoming.paginate(page: params[:page], per_page: 2).order(created_at: :desc)
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.valid? && @event.save
      redirect_to user_path(current_user), notice: 'Event Created Successfully'
    else
      render 'new'
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(username: params[:session][:username])
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'You have successfully Logged in!'
      redirect_to events_path
    else
      flash[:error] = 'Invalid email or password'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'Logged out'
    redirect_to root_path
  end

  def index
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorization, only: [:show]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid? && @user.save
      redirect_to login_path, notice: 'Account created successfuly, login using your credentials'
    else
      render 'new'
    end
  end

  def show
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_buttons
    buttons = []
    if logged_in?
      buttons.push(link_to(current_user.username, user_path(current_user),
                           class: 'text-light mr-2 bg-success py-1 px-3'))
      buttons.push(link_to('Create Event', new_event_path, class: 'text-light mr-2 bg-success py-1 px-3'))
      buttons.push(link_to('Logout', logout_path, method: :delete, class: 'text-light mr-2 bg-success py-1 px-3'))
    else
      buttons.push(link_to('Login', login_path, class: 'text-light mr-2 bg-success py-1 px-3'))
      buttons.push(link_to('Sign Up', new_user_path, class: 'text-light mr-2 bg-success py-1 px-3'))
    end
    buttons
  end

  def user_attending?(event_id)
    buttons = []
    if current_user.events.find_by(id: :event_id)
      buttons.push(link_to('Enroll', attendances_path(controller: 'attendances', action: 'create', event_id: event_id),
                           method: :post, class: 'btn btn-outline-success'))
      buttons.push(link_to('cancel', attendance_path(event_id),
                           method: :delete, class: 'btn btn-outline-danger mt-1'))
    else
      buttons.push(link_to('Enroll', attendances_path(controller: 'invites', action: 'create', event_id: event_id),
                           method: :post, class: 'btn btn-outline-success'))
      buttons.push(link_to('Cancel', attendance_path(event_id), method: :delete, class: 'btn btn-outline-danger mt-1'))
    end
    buttons
  end
end

app/views/events/_futureevents.html.erb
<%@upcoming_events.each do |event|%>
<div class="col-sm-12 col-md-6">
      <%= link_to event_path(event), class:'text-decoration-none' do%>
      <div class="card bg-light mb-4 hover-1">
        <div class="card-title text-dark light-red">
          <div class="text-white px-2 py-1 d-flex justify-content-between align-items-center">
            <h4><%= event.title.capitalize%></h4>
            <p>Creator : <%=event.creator.username%></p>
          </div>
        </div>
        <div class="card-body bg-light text-dark px-0">
          <p class="text-justify px-2"><%=event.description%></p>
        </div>
        <div class="card-footer text-dark px-2 light-red">
          <p class="text-white">Event Date: <%= event.date%></p>
        <div class="mt-3">
          <% user_attending?(event.id).each do |button| %>
            <%= button%>
          <%end%>
        </div>
      </div>
  </div>
      <%end%>
</div>
<%end%>

app/views/events/_nextevents.html.erb
<%@upcoming_events.each do |event|%>
<div class="col-md-6">
      <%= link_to event_path(event), class:'text-decoration-none' do%>
      <div class="card bg-light mb-4 hover-1">
        <div class="">
          <div class="card text-center shadow mb-5 rounded">
            <h4><%= event.title.capitalize%></h4>
            <p>Creator : <%=event.creator.username%></p>
          </div>
        </div>
        <div class="card-body text-dark px-0">
          <p class="text-justify px-2"><%=event.description%></p>
        </div>
        <div class="card-footer text-dark px-2 light-red">
          <p class="text-dark">Event Date: <%= event.date%></p>
        <div class="mt-3">
          <% user_attending?(event.id).each do |button| %>
            <%= button%>
          <%end%>
        </div>
      </div>
  </div>
      <%end%>
</div>
<%end%>

app/views/events/_pastevents.html.erb
<%@past_events.each do |event|%>
<div class="col-md-6">
      <%= link_to event_path(event), class:'text-decoration-none' do%>
      <div class="card bg-light mb-4 hover-1">
        <div class="card-title text-dark light-red">
          <div class="text-dark px-2 py-1 d-flex justify-content-between align-items-center">
            <h4><%= event.title.capitalize%></h4>
            <p>Creator : <%=event.creator.username%></p>
          </div>
        </div>
        <div class="card-body bg-light text-dark px-0">
          <p class="text-justify px-2"><%=event.description%></p>
        </div>
        <div class="card-footer light-red text-dark px-2">
          <p class="text-dark">Event Date: <%= event.date%></p>
      </div>
  </div>
      <%end%>
</div>
<%end%>

app/views/events/index.html.erb
<div class="container">
  <h1 class="p-2 w-50 mx-auto mb-2 text-center text-white">
    Upcoming events: <%=pluralize(@upcoming_events.count, 'Event')%>
  </h1>
  <div class="row pt-5 text-center shadow mb-5 bg-info rounded justify-content-md-center">
    <%= render "nextevents"%>
    <div class="flickr_pagination mb-4">
      <%= will_paginate @upcoming_events%>
    </div>
  </div>


  <h1 class="p-2 w-50 mx-auto mb-2 text-center text-white">
    Past events: <%=pluralize(@past_events.count, 'Event')%>
  </h1>
  <div class="row pt-5 text-center shadow mb-5 bg-info rounded justify-content-md-center">
    <%=render "pastevents" %>
    <div class="flickr_pagination mb-4">
    <%= will_paginate @past_events%>
    </div>
  </div>

</div>

app/views/events/new.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @event %>
      <%= form_with(model: @event, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :date, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.date_field :date, class:"form-control shadow rounded"%>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div> 

app/views/events/show.html.erb
<h2 class = 'text-center mt-4'><%=@event.title%></h2>

  <div class = 'container'>
    <div class = 'row justify-content-md-center'>
      <div class = 'col-8 mt-4'>
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            created by <%= @event.creator.username%>
          </div>
          <div class="card-body">
            <div class="card-text text-center"><%= simple_format(@event.description) %></div>
            <div class="text-dark">Event Date: <%= @event.date%></div>
          </div>
          <div class="card-body">
            <p class="align-self-center text-dark">Number of people attending: <%= @event.attendees.count%></p>
            <% if @event.attendees.count == 0 %>
              <%"Nothing to show"%>
              <% else %>
              <h6 class="text-dark">List of names:</h6>
              <% @event.attendees.each do |attendee|%>
                <ul class="list-unstyled text-dark">
                  <li><%= attendee.username%></li>
                </ul>
              <% end %>
            <%end%>
          </div>
        </div>
        </div>
    </div>
  </div>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div> 

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

    <%= link_to 'Private-Blog', events_path, class: 'navbar-brand' %>
  <ul class="navbar-nav ml-auto">
    <li>
      <% display_buttons.each do |button|%>
        <%= button%>
      <%end%>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private-Events</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navbar'%>
    <div id = page-content>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %> 

app/views/users/new.html.erb
<h1 class='text-center mt-4'> Sign up </h1>
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-10"">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
          </div>
        </div>
        
        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.password_field :password, rows: 10, class: "form-control shadow rounded", placeholder: "Enter your password" %>
          </div>
        </div>
        
        <div class="form-group row">
          <%= f.label :password_confirmation, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.password_field :password_confirmation, class: "form-control shadow rounded", placeholder: "Confirm password" %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit "Sign up",class:"btn btn-outline-light btn-lg" %>
        </div>
  
      <% end %>
    </div>
    
  </div>
</div> 

app/views/users/show.html.erb
<h2 class = 'text-center mt-4'>Events History</h2>

  <div class = 'container'>
    <div class = 'row justify-content-md-center'>
      <div class = 'col-8 mt-4'>
        <div class="card text-center shadow mb-5 bg-info rounded">
          <div>
           <h4 class="p-2 w-50 mx-auto mb-2 text-center text-white"> Events you created: <%= events_created.count%></h4>
          </div>
          <% events_created.order('created_at DESC').each do |event|%>
            <div class="col-sm-12">
              <%= link_to event_path(event), class:'text-decoration-none' do%>
                <div class="card light-red mb-4 text-center">
                  <div class="card-title text-dark py-2">
                    <p class="h4">Event Title:- <%= event.title%></p>
                  </div>
                  <div class="card-footer bg-light text-dark px-2">
                    <small class="">Date: [<%= event.date%>] </small>
                  </div>
                </div>
              <%end%>
           </div>
          <%end%>

          <h4 class="p-2 w-50 mx-auto mb-2 text-center text-white">Upcoming Events: <%= events_attendance.where('date>?', Time.now).count%></h4>
          <% events_attendance.where('date>?', Time.now).each do |event|%>
            <div class="col-sm-12">
              <%= link_to event_path(event), class:'text-decoration-none' do%>
                <div class="card light-red mb-4 text-center">
                  <div class="card-title text-dark py-2">
                    <p class="h4">Event Title:- <%= event.title%></p>
                  </div>
                  <div class="card-footer bg-light text-dark px-2">
                      <small class="">Event will be held in <%= time_ago_in_words(event.date)%> [<%= event.date%>] </small>
                  </div>
                </div>
              <%end%>
           </div>
          <%end%>

          <h4 class="p-2 w-50 mx-auto mb-2 text-center text-white">Previously attended: <%= events_attendance.where('date<?', Time.now).count%></h4>
          <% events_attendance.where('date<?', Time.now).each do |event|%>
            <div class="col-sm-12">
              <%= link_to event_path(event), class:'text-decoration-none' do%>
                <div class="card light-red mb-4 text-center">
                  <div class="card-title text-dark py-2">
                    <p class="h4">Event Title:- <%= event.title%></p>
                  </div> 
                    <small class="">Event will be held in <%= time_ago_in_words(event.date)%> [<%= event.date%>] </small>
                  </div>
                </div>
              <%end%>
           </div>
          <%end%>

        </div>
      </div>
    </div>
  </div>